### ISSUE TITLE
[Webpack Issue] The path resolve problem in build stage

### ISSUE THREAD

**Issue by whats2000** [opengovsg/pdf2md#92] opened 2024-09-18 14:17 UTC
**Describe the bug**
This bug will trigger the following error at deployment time
```
[ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received type number (91100)
```

**To Reproduce**
1. Use webpack to build the project
2. Invoke the `pdf2md` function
3. See the error at the console

**Expected behavior**
The path dependence seems will break when using `webpack` to build the production, which the same code work smoothly at development mode

**Screenshots**
![image](https://github.com/user-attachments/assets/36143d81-8ebe-488c-9bf0-cc2df1a6a092)

**Desktop (please complete the following information):**
 - OS: Window
 - VSCode
 - Version 1.93.0

**Additional context**
Yes, seems like the path in the dependence really mass up, I have tried to mark it as `externals`, but sadly it does not work for me.
[Related Issue: Support Webpack, don't use require.resolve() #76](https://github.com/opengovsg/pdf2md/issues/76)

**Comment by LoneRifle** [comment] 2024-11-27 06:05
Please try this with v0.2.0 of this package, which removes the dependency on node-specific libs, including `path`.

**Comment by LoneRifle** [comment] 2024-12-10 23:59
I'll just track this via #76 for now.

Duplicate of #76

**Closed by LoneRifle** 2024-12-10 23:59 UTC
